[ignore]
glob = ['*.sch', '*.cxx']

regex = [
    # Ignore files and directories matching these regex patterns.
    # See https://learnbyexample.github.io/python-regex-cheatsheet/
    # for example: regex = ['.*\.toml$']
]
